version: '3.7'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: grievanceai
      POSTGRES_PASSWORD: grievanceaipassword
      POSTGRES_DB: grievanceai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
